import { AsyncLocalStorage } from 'async_hooks';
import { trace } from '@opentelemetry/api';
import { randomUUID } from 'crypto';

/**
 * Trace context for correlation across async operations
 */
export interface TraceContext {
  /**
   * OpenTelemetry trace ID (from active span)
   */
  traceId?: string;

  /**
   * OpenTelemetry span ID (from active span)
   */
  spanId?: string;

  /**
   * Correlation ID for request tracking across services
   * This is a business-level ID that may be generated by API gateway or first service
   */
  correlationId?: string;

  /**
   * Event ID (for Service Bus messages or similar event-driven flows)
   */
  eventId?: string;

  /**
   * Event type (for Service Bus messages or similar event-driven flows)
   */
  eventType?: string;

  /**
   * User ID (if authenticated request)
   */
  userId?: string;

  /**
   * Request ID (unique per HTTP request, typically from x-request-id header)
   */
  requestId?: string;

  /**
   * Custom context fields
   */
  [key: string]: string | undefined;
}

/**
 * AsyncLocalStorage for maintaining trace context across async operations
 * This works automatically with async/await, Promises, and callbacks
 */
const asyncLocalStorage = new AsyncLocalStorage<TraceContext>();

/**
 * Get the current trace context from AsyncLocalStorage and active span
 * 
 * Automatically includes trace ID and span ID from active OpenTelemetry span if available.
 * 
 * @example
 * ```typescript
 * const { traceId, spanId, correlationId } = getCurrentTraceContext();
 * logger.info('Processing request', { traceId, correlationId });
 * ```
 */
export function getCurrentTraceContext(): TraceContext {
  const storedContext = asyncLocalStorage.getStore() || {};

  // Try to get trace ID and span ID from active span
  const activeSpan = trace.getActiveSpan();
  if (activeSpan) {
    const spanContext = activeSpan.spanContext();
    if (spanContext) {
      return {
        ...storedContext,
        traceId: storedContext.traceId || spanContext.traceId,
        spanId: storedContext.spanId || spanContext.spanId,
      };
    }
  }

  return storedContext;
}

/**
 * Set trace context for current async execution
 * 
 * Merges with existing context rather than replacing it.
 * 
 * @example
 * ```typescript
 * setTraceContext({
 *   correlationId: req.headers['x-correlation-id'],
 *   userId: req.user?.id,
 * });
 * ```
 */
export function setTraceContext(context: Partial<TraceContext>): void {
  const currentContext = asyncLocalStorage.getStore() || {};
  const newContext = { ...currentContext, ...context };
  asyncLocalStorage.enterWith(newContext);
}

/**
 * Run function with trace context
 * 
 * Creates a new AsyncLocalStorage context for the duration of the function.
 * All code executed within the function (including async operations) will have access to this context.
 * 
 * @example
 * ```typescript
 * await runWithTraceContext(
 *   { correlationId: 'abc-123', userId: 'user-456' },
 *   async () => {
 *     await processMessage();
 *     // All logs and traces here will include correlationId and userId
 *   }
 * );
 * ```
 */
export async function runWithTraceContext<T>(
  context: TraceContext,
  fn: () => Promise<T>
): Promise<T> {
  return asyncLocalStorage.run(context, fn);
}

/**
 * Extract trace ID from W3C traceparent header
 * 
 * W3C Trace Context format: 00-{trace-id}-{parent-id}-{flags}
 * https://www.w3.org/TR/trace-context/
 * 
 * @param traceparent - W3C traceparent header value
 * @returns Extracted trace ID or undefined
 * 
 * @example
 * ```typescript
 * const traceId = extractTraceIdFromTraceparent(req.headers.traceparent);
 * ```
 */
export function extractTraceIdFromTraceparent(traceparent: string | undefined): string | undefined {
  if (!traceparent) return undefined;

  const parts = traceparent.split('-');
  if (parts.length >= 2 && parts[0] === '00') {
    return parts[1]; // Return trace-id part
  }

  return undefined;
}

/**
 * Extract correlation ID from various header formats
 * 
 * Tries common correlation ID headers:
 * - x-correlation-id (preferred)
 * - x-request-id
 * - x-amzn-trace-id
 * - x-b3-traceid
 * 
 * @param headers - HTTP headers object
 * @returns Extracted correlation ID or undefined
 */
export function extractCorrelationId(
  headers: Record<string, string | string[] | undefined>
): string | undefined {
  const headerNames = [
    'x-correlation-id',
    'x-request-id',
    'correlation-id',
    'correlationid',
    'x-amzn-trace-id',
  ];

  for (const headerName of headerNames) {
    const value = headers[headerName] || headers[headerName.toLowerCase()];
    if (value) {
      return Array.isArray(value) ? value[0] : value;
    }
  }

  return undefined;
}

/**
 * Generate a new correlation ID (UUID v4)
 * 
 * @returns New correlation ID
 */
export function generateCorrelationId(): string {
  return randomUUID();
}

/**
 * Inject trace context into HTTP headers for outgoing requests
 * 
 * Adds:
 * - x-correlation-id: Correlation ID from context
 * - traceparent: W3C trace context (automatically handled by OpenTelemetry instrumentation)
 * 
 * @param headers - Existing headers object (will be mutated)
 * @returns Updated headers object
 * 
 * @example
 * ```typescript
 * const headers = { 'content-type': 'application/json' };
 * injectTraceHeaders(headers);
 * // Now headers include x-correlation-id
 * ```
 */
export function injectTraceHeaders(
  headers: Record<string, string> = {}
): Record<string, string> {
  const context = getCurrentTraceContext();

  if (context.correlationId) {
    headers['x-correlation-id'] = context.correlationId;
  }

  if (context.requestId) {
    headers['x-request-id'] = context.requestId;
  }

  // Note: traceparent is automatically injected by OpenTelemetry HTTP instrumentation
  // But if you need to manually inject it (e.g., for non-HTTP protocols):
  const activeSpan = trace.getActiveSpan();
  if (activeSpan) {
    const spanContext = activeSpan.spanContext();
    if (spanContext) {
      // W3C Trace Context format
      headers['traceparent'] = `00-${spanContext.traceId}-${spanContext.spanId}-${
        spanContext.traceFlags.toString(16).padStart(2, '0')
      }`;
    }
  }

  return headers;
}

/**
 * Inject trace context into Azure Service Bus message properties
 * 
 * Adds:
 * - traceparent: W3C trace context for distributed tracing
 * - correlationId: Correlation ID from context
 * - Other context fields (eventId, eventType, etc.)
 * 
 * @param properties - Service Bus message application properties (will be mutated)
 * @returns Updated properties object
 * 
 * @example
 * ```typescript
 * const message = {
 *   body: { ... },
 *   applicationProperties: {}
 * };
 * injectTraceIntoServiceBusMessage(message.applicationProperties);
 * ```
 */
export function injectTraceIntoServiceBusMessage(
  properties: Record<string, unknown> = {}
): Record<string, unknown> {
  const context = getCurrentTraceContext();

  if (context.correlationId) {
    properties.correlationId = context.correlationId;
  }

  if (context.eventId) {
    properties.eventId = context.eventId;
  }

  if (context.eventType) {
    properties.eventType = context.eventType;
  }

  if (context.userId) {
    properties.userId = context.userId;
  }

  // Inject W3C trace context
  const activeSpan = trace.getActiveSpan();
  if (activeSpan) {
    const spanContext = activeSpan.spanContext();
    if (spanContext) {
      properties.traceparent = `00-${spanContext.traceId}-${spanContext.spanId}-${
        spanContext.traceFlags.toString(16).padStart(2, '0')
      }`;
      if (spanContext.traceState) {
        properties.tracestate = spanContext.traceState.serialize();
      }
    }
  }

  return properties;
}

/**
 * Extract trace context from Azure Service Bus message properties
 * 
 * Extracts:
 * - traceparent: W3C trace context
 * - correlationId
 * - eventId
 * - eventType
 * - userId
 * 
 * @param properties - Service Bus message application properties
 * @returns Extracted trace context
 */
export function extractTraceFromServiceBusMessage(
  properties: Record<string, unknown>
): TraceContext {
  return {
    traceId: extractTraceIdFromTraceparent(properties.traceparent as string),
    correlationId: properties.correlationId as string,
    eventId: properties.eventId as string,
    eventType: properties.eventType as string,
    userId: properties.userId as string,
  };
}

/**
 * Clear trace context (useful for testing)
 */
export function clearTraceContext(): void {
  asyncLocalStorage.disable();
}
